# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

# Default values for fybrik-implicit-copy-batch
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# blueprint_namespace: default
# blueprint_name: mybp
# app_name:
# app_namespace:
# app_cluster:
labels: {}

image: "ghcr.io/fybrik/mover:latest"
imagePullPolicy: null
noFinalizer: "true"

# copies from source
copy:
  source:
    vault: {}
    connection:
      s3: {}
#        endpoint: ""
#        bucket: ""
#        object_key: ""
#    format: ""
#    vault: {}

  # copies to destination
  destination:
    vault: {}
    connection:
      s3: {}
#        endpoint: ""
#        bucket: ""
#        object_key: ""
#    format: ""
#    vault: {}

  transformations: []
  readDataType: "LogData"
  writeDataType: "LogData"
  writeOperation: "Overwrite"