apiVersion: app.fybrik.io/v12
kind: FybrikApplication
metadata:
  name: notebook-with-kubeflow
  labels:
    app: kf-notebook
spec:
  selector:
    clusterName: thegreendragon
    workloadSelector:
      matchLabels:
        app: kf-notebook
  appInfo:
    intent: Fraud Detection
    role: Security
  data:
    - dataSetID: "{\"ServerName\":\"mds1\",\"AssetGuid\":\"ASSET_ID\"}"
      requirements:
        interface: 
          protocol: fybrik-arrow-flight
