apiVersion: app.m4d.ibm.com/v1alpha1
kind: M4DApplication
metadata:
  name: notebook-with-kubeflow
  labels:
    app: kf-notebook
spec:
  selector:
    clusterName: US-cluster
    workloadSelector:
      matchLabels:
        app: kf-notebook
  appInfo:
    intent: fraud-detection
    role: Security
  data:
    - dataSetID: "{\"ServerName\":\"cocoMDS3\",\"AssetGuid\":\"ASSET_ID\"}"
      requirements:
        interface: 
          protocol: m4d-arrow-flight
          dataformat: arrow
