apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.1
  name: fybrikstorageaccounts.app.fybrik.io
spec:
  group: app.fybrik.io
  names:
    kind: FybrikStorageAccount
    listKind: FybrikStorageAccountList
    plural: fybrikstorageaccounts
    singular: fybrikstorageaccount
  scope: Namespaced
  versions:
    - name: v1beta1
      schema:
        openAPIV3Schema:
          description: FybrikStorageAccount defines a storage account used for copying data. Only S3 based storage is supported. It contains endpoint, region and a reference to the credentials a Owner of the asset is responsible to store the credentials
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: FybrikStorageAccountSpec defines the desired state of FybrikStorageAccount
              properties:
                endpoint:
                  description: Endpoint for accessing the data
                  type: string
                id:
                  description: Identification of a storage account
                  type: string
                region:
                  description: Storage region
                  type: string
                secretRef:
                  description: A name of k8s secret deployed in the control plane. This secret includes secretKey and accessKey credentials for S3 bucket
                  type: string
              required:
                - endpoint
                - id
                - region
                - secretRef
              type: object
            status:
              description: FybrikStorageAccountStatus defines the observed state of FybrikStorageAccount
              type: object
          required:
            - spec
          type: object
      served: true
      storage: true
