# Default values for Fybrik.
# This is a YAML-formatted file.
# It overrides values that are different from the default values.yaml

# Global configuration applies to multiple components installed by this chart
global:
  hub: localhost:5000/fybrik-system
  tag: "0.0.0"
  imagePullPolicy: "Always"

  prettyLogging: false
  # zerolog verbosity level 
  # ref: https://github.com/rs/zerolog#leveled-logging
  loggingVerbosity: -1

# Cluster metadata values
cluster:
  # Set to the name of the cluster.
  name: kind-kind
  # Set to cluster zone.
  zone: localhost
  # Set to cluster region.
  region: homeoffice
  # Set to the cluster Vault auth method path.
  vaultAuthPath: kind

# Configuration when deploying to a coordinator cluster.
coordinator:
  enabled: false

# Manager component
manager:
  # Set to true to enable socat in the manager pod to forward
  # traffic from a localhost registry. Used only for development and integration tests.
  socat: true

# OPA connector component
opaConnector:
  # Image name or a hub/image[:tag]
  image: "serverpolicymanager-mock"

# Katalog connector component
katalogConnector:
  # Image name or a hub/image[:tag]
  image: "data-catalog-mock"

# Storage allocation and management
storageManager:
  enabled: false
