# Default values for Fybrik.
# This is a YAML-formatted file.
# It overrides values that are different from the default values.yaml
# The values used for testing read flow where the manager and connectors
# uses mutual tls connection. In addition, OPA and Vault servers are configured to use
# mutual tls. Openmetadata server is not configured with TLS.

# Global configuration applies to multiple components installed by this chart
global:
  hub: localhost:5000/fybrik-system
  tag: "0.0.0"
  imagePullPolicy: "Always"

  prettyLogging: false
  # zerolog verbosity level 
  # ref: https://github.com/rs/zerolog#leveled-logging
  loggingVerbosity: -1

coordinator:
  catalogConnectorURL: https://openmetadata-connector:8443
  policyManagerConnectorURL: https://opa-connector:8443
  vault:
    # Vault is configured to use TLS.
    address: "https://vault.fybrik-system:8200"

# Manager component
manager:
  # Set to true to enable socat in the manager pod to forward
  # traffic from a localhost registry. Used only for development and integration tests.
  socat: true
  tls:
    certs:
      certSecretName: "test-tls-manager-certs"
      cacertSecretName: "test-tls-ca-certs"

openmetadataConnector:
  service:
    port: 8443
       
  tls:
    use_tls: true
    use_mtls: true
    certs:
      certSecretName: "test-tls-openmetadata-connector-certs"
      cacertSecretName: "test-tls-ca-certs"

opaConnector:
  # OPA server is configured to use mutual TLS.
  serverURL: https://opa:8443
  tls:
    use_tls: true
    use_mtls: true
    certs:
      certSecretName: "test-tls-opa-connector-certs"
      cacertSecretName: "test-tls-ca-certs"
  service:
    port: 8443

opaServer:

  tls:
    use_tls: true
    certs:
      certSecretName: "test-tls-opa-server-certs"
      cacertSecretName: "test-tls-ca-certs"

  # In OPA server, liveness is defined by HTTPS request when using mtls
  # which means that certificates verification is required
  # between kubelet (the client) and OPA server.
  # Avoid configurating kubelet by setting enabled to false.
  enableLivenessProbe: false
  # In OPA server, readiness is defined by HTTPS request when using mtls
  # which means that certificates verification is required
  # between kubelet (the client) and OPA server.
  # Avoid configurating kubelet by setting enabled to false.
  enableReadinessProbe: false
  image: "openpolicyagent/opa:0.36.0-debug"
  #  the following options configure OPA with TLS
  args:
  - "run"
  - "--server"
  - "--log-level=debug"
  - "--set=decision_logs.console=true"
  - "--tls-cert-file=/data/tls-cert/tls.crt"
  - "--tls-private-key-file=/data/tls-cert/tls.key"
  - "--addr=https://0.0.0.0:8443"

  service:
    port: 8443

  # Bootstrap policies to load upon startup
  bootstrapPolicies:
    notebookSamplePolicy: |-
      package dataapi.authz

      rule[{}] {
        description := "allow read datasets with no tags"
        input.action.actionType == "read"
        not input.resource.metadata.tags
      }

      rule[{"action": {"name":"RedactAction", "columns": column_names}, "policy": description}] {
        description := "While reading redact columns tagged as PII in datasets tagged with finance = true"
        input.action.actionType == "read"
        input.resource.metadata.tags.finance
        column_names := [input.resource.metadata.columns[i].name | input.resource.metadata.columns[i].tags.PII]
      }


# S3 mock service installed in fybrik namespace
s3mock:
  enabled: true

