# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

language: go

services:
- docker

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - python3-setuptools
      - asciidoctor
      - conntrack
      - ethtool
      - apache2-utils

os:
- linux

go:
- "1.13"

git:
  depth: 3

cache:
  directories:
  - $GOPATH/pkg/mod
  - $HOME/.m2
  - $HOME/gopath/src/github.com/ibm/the-mesh-for-data/hack/tools/bin

go_import_path: github.com/ibm/the-mesh-for-data

# Install must be set to prevent default `go get` to run.
# The dependencies have already been vendored by `dep` so
# we don't need to fetch them.
install:
-

jobs:
  include: 
  - stage: Build
    name: "Verify code"
    install:
    - make install-tools
    script:
    - make verify

  - stage: Build
    name: "Run unit tests"
    install:
    - make install-tools
    script:
    - make docker-mirror-read
    - make test

  # FIXME(hunchback): disabled as its' taking 15m to run
  # - stage: verify-license
  #   install:
  #   script:
  #   - make license

  # The following integration/system test builds all images
  # and deploys all the services locally in a kind environment
  # It then runs integration tests that run requests against the installed system
  # These requests can be CRDs to K8s api-server or other requests to other endpoints.
  - stage: Test
    name: "Integration tests for manager in kind"
    env:
    - DOCKER_HOSTNAME=localhost:5000
    - DOCKER_NAMESPACE=m4d-system
    install:
    - make install-tools
    script:
    - make docker-mirror-read
    - make run-integration-tests
    deploy:
     skip_cleanup: true
     provider: script
     script: sudo chmod o+x /etc/docker && make docker-retag-and-push-public && make helm-push-public
     on:
       condition: $TRAVIS_PULL_REQUEST = false
       branch: master

  - stage: Publish
    name: "Build and publish website"
    env:
    - WEBSITE_LOCAL_DIR=public
    script:
    - make -C website
    deploy:
      skip_cleanup: true
      provider: pages
      local_dir: website/$WEBSITE_LOCAL_DIR
      github_token: $GITHUB_TOKEN # generate with: public_repo or repo scope (for personal repo)
      on:
        branch: master

  - stage: Deploy
    name: "Kind deploy"
    install:
    - make install-tools
    script:
    - make docker-mirror-read
    - make run-deploy-tests
    if: branch = master AND type = push

notifications:
  email: false
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN # generate with: public_repo or repo scope (for personal repo)
  file:
  - README.md
  skip_cleanup: 'true'
  on:
    tags: true
