{{- if include "m4d.isEnabled" (tuple .Values.manager.enabled (or .Values.coordinator.enabled .Values.worker.enabled)) }}
{{- if .Values.manager.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.manager.serviceAccount.name }}
  labels:
    app.kubernetes.io/component: manager
    {{- include "m4d.labels" . | nindent 4 }}
  {{- with .Values.manager.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
