{{- if include "m4d.isEnabled" (tuple .Values.manager.enabled .Values.coordinator.enabled) }}
{{- if include "m4d.isRazeeEnabled" . }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: razee-credentials
data:
  {{ if .Values.coordinator.razee.multiclusterGroup }}
  MULTICLUSTER_GROUP: {{ .Values.coordinator.razee.multiclusterGroup | b64enc }}
  {{ end }}
  {{ if .Values.coordinator.razee.url }}
  RAZEE_URL: {{ .Values.coordinator.razee.url | b64enc }}
  {{ end }}
  {{ if .Values.coordinator.razee.user }}
  RAZEE_USER: {{ .Values.coordinator.razee.user | b64enc }}
  {{ end }}
  {{ if .Values.coordinator.razee.password }}
  RAZEE_PASSWORD: {{ .Values.coordinator.razee.password | b64enc }}
  {{ end }}
  {{ if .Values.coordinator.razee.apiKey }}
  API_KEY: {{ .Values.coordinator.razee.apiKey | b64enc }}
  {{ end }}
  {{ if .Values.coordinator.razee.iamKey }}
  IAM_API_KEY: {{ .Values.coordinator.razee.iamKey | b64enc }}
  {{ end }}
{{- end }}
{{- end }}