# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

# Default values for m4d-kafka.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# metadata associated with k8s resources
metadata:
  name: "kafka"
  namespace: "default"
  labels: []

# copies from source
source:
  connection:
    kafka:
      bootstrap_servers: ""
      schema_registry: ""
      topic_name: ""
      ssl_truststore: ""
      ssl_truststore_password: ""
      security_protocol: ""
      sasl_mechanism: ""
      key_deserializer: ""
      value_deserializer: ""
  credentialLocation: ""
  format: ""

# copies to destination
destination:
  connection:
    s3:
      endpoint: ""
      bucket: ""
      object_key: ""
  format: ""
  credentialLocation: ""
