# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: m4d-config
data:
  SECRET_PROVIDER_URL: "http://secret-provider.m4d-system:5555/get-secret"
  SECRET_PROVIDER_ROLE: "demo"
  #catalog connector
  CATALOG_CONNECTOR_URL: "egr-connector:50084"
  CATALOG_PROVIDER_NAME: "EGERIA"

  #credentials manager connector
  CREDENTIALS_CONNECTOR_URL: "vault-connector:50083"
  CREDENTIALS_PROVIDER_NAME: "VAULT"

  #policy-compiler and policy manager connectors
  MAIN_POLICY_MANAGER_CONNECTOR_URL: "opa-connector:50082"
  MAIN_POLICY_MANAGER_NAME: "OPA"
  USE_EXTENSIONPOLICY_MANAGER: "false"
  #EXTENSIONS_POLICY_MANAGER_CONNECTOR_URL: "opa-connector:50082"
  #EXTENSIONS_POLICY_MANAGER_NAME: "OPA"

  #internal vault related variables
  VAULT_ADDRESS: "http://vault.m4d-system:8200/"
  VAULT_DATASET_HOME: "m4d/dataset-creds/"
  VAULT_USER_HOME: "m4d/user-creds/"
  VAULT_DATASET_MOUNT: "v1/sys/mounts/m4d/dataset-creds"
  VAULT_USER_MOUNT: "v1/sys/mounts/m4d/user-creds"
  VAULT_TTL: "24h"
  VAULT_AUTH: "kubernetes"
  MODULES_ROLE: "module"

  #timeout for all the connectors
  CONNECTION_TIMEOUT: "120"

  #external services
  OPA_SERVER_URL: "opa:8181"
  EGERIA_SERVER_URL: "https://lab-core.egeria-catalog:9443"

  #external vault  variables
  USER_VAULT_ADDRESS: "http://vault:8200/"
  USER_VAULT_PATH: "external"
  POLICY_TO_BE_EVALUATED: "sample_policies"
