---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault
subjects:
- kind: ServiceAccount
  name: vault
  namespace: m4d-system
roleRef:
  kind: ClusterRole
  name: vault-secrets-manager
  apiGroup: rbac.authorization.k8s.io
