plugins:
  # Settings related to vault-plugin-secrets-kubernetes-reader plugin  
  vaultPluginSecretsKubernetesReader:
    enabled: true
    # If true secrets can be read from any namespace. Otherwise they can be read only from
    # selected namespaces listed in namespaces field.
    clusterScope: true
    # A list of namespaces that Vault can read Kuberenets secrets from.
    namespaces: 
      #- m4d-notebook-sample
      #- m4d-system
    
