{{- $autoFlag := and .Values.coordinator.enabled (eq .Values.coordinator.policyManager "opa") }}
{{- if include "fybrik.isEnabled" (tuple .Values.openPolicyAgentConnector.enabled $autoFlag) }}
{{- if .Values.openPolicyAgentConnector.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.openPolicyAgentConnector.serviceAccount.name }}
  labels:
    app.kubernetes.io/component: openpolicyagent-connector
    {{- include "fybrik.labels" . | nindent 4 }}
  {{- with .Values.openPolicyAgentConnector.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
