{{- $autoFlag := and .Values.coordinator.enabled (eq .Values.coordinator.policyManager "opa") }}
{{- if include "fybrik.isEnabled" (tuple .Values.openPolicyAgentConnector.enabled $autoFlag) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openpolicyagent-connector
  labels:
    app.kubernetes.io/component: openpolicyagent-connector
    {{- include "fybrik.labels" . | nindent 4 }}
spec:
  {{- if not .Values.openPolicyAgentConnector.autoscaling.enabled }}
  replicas: {{ .Values.openPolicyAgentConnector.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: openpolicyagent-connector
      {{- include "fybrik.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.openPolicyAgentConnector.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        fybrik.io/componentType: connector
        app.kubernetes.io/component: openpolicyagent-connector
        {{- include "fybrik.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.openPolicyAgentConnector.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.openPolicyAgentConnector.podSecurityContext | nindent 8 }}
      containers:
        - name: openpolicyagent-connector
          securityContext:
            {{- toYaml .Values.openPolicyAgentConnector.securityContext | nindent 12 }}
          image: {{ include "fybrik.image" ( tuple $ .Values.openPolicyAgentConnector ) }}
          imagePullPolicy: {{ .Values.openPolicyAgentConnector.imagePullPolicy | default .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          envFrom:
            - configMapRef:
                name: openpolicyagent-connector-config
          resources:
            {{- toYaml .Values.openPolicyAgentConnector.resources | nindent 12 }}
      {{- with .Values.openPolicyAgentConnector.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.openPolicyAgentConnector.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.openPolicyAgentConnector.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
