{{- $autoFlag := and .Values.coordinator.enabled (eq .Values.coordinator.policyManager "opa") }}
{{- if include "fybrik.isEnabled" (tuple .Values.openPolicyAgentConnector.enabled $autoFlag) }}
apiVersion: v1
kind: Service
metadata:
  name: openpolicyagent-connector
  labels:
    app.kubernetes.io/component: openpolicyagent-connector
    {{- include "fybrik.labels" . | nindent 4 }}
spec:
  type: {{ .Values.openPolicyAgentConnector.service.type }}
  ports:
    - port: {{ .Values.openPolicyAgentConnector.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: openpolicyagent-connector
    {{- include "fybrik.selectorLabels" . | nindent 4 }}
{{- end }}
