apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: '{{ .Release.Namespace }}-validating-webhook'
  annotations:
    cert-manager.io/inject-ca-from: '{{ .Release.Namespace }}/serving-cert'
    certmanager.k8s.io/inject-ca-from: '{{ .Release.Namespace }}/serving-cert'
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: webhook-service
        namespace: '{{ .Release.Namespace }}'
        path: /validate-app-fybrik-io-v1beta1-fybrikapplication
    failurePolicy: Fail
    name: vfybrikapplication-v1.kb.io
    rules:
      - apiGroups:
          - app.fybrik.io
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - fybrikapplications
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: webhook-service
        namespace: '{{ .Release.Namespace }}'
        path: /validate-app-fybrik-io-v1beta1-fybrikmodule
    failurePolicy: Fail
    name: vfybrikmodule-v1beta1.kb.io
    rules:
      - apiGroups:
          - app.fybrik.io
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - fybrikmodules
    sideEffects: None
