apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.7.0
  name: assets.katalog.fybrik.io
spec:
  group: katalog.fybrik.io
  names:
    kind: Asset
    listKind: AssetList
    plural: assets
    singular: asset
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Asset defines an asset in the catalog
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              properties:
                details:
                  description: Asset details
                  properties:
                    connection:
                      description: Connection information
                      properties:
                        name:
                          description: Name of the connection to the data source
                          type: string
                      required:
                        - name
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    dataFormat:
                      description: Data format
                      type: string
                  required:
                    - connection
                  type: object
                metadata:
                  description: Asset metadata
                  properties:
                    columns:
                      description: Columns associated with the asset
                      items:
                        description: ResourceColumn represents a column in a tabular resource
                        properties:
                          name:
                            description: Name of the column
                            type: string
                          tags:
                            description: Tags associated with the column
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                        required:
                          - name
                        type: object
                      type: array
                    geography:
                      description: Geography of the resource
                      type: string
                    name:
                      description: Name of the resource
                      type: string
                    owner:
                      description: Owner of the resource
                      type: string
                    tags:
                      description: Tags associated with the asset
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                  type: object
                secretRef:
                  description: Reference to a Secret resource holding credentials for this asset
                  properties:
                    name:
                      description: Name of the Secret resource
                      type: string
                    namespace:
                      description: Namespace of the Secret resource. If it is empty then the asset namespace is used.
                      type: string
                  required:
                    - name
                  type: object
              required:
                - details
                - metadata
                - secretRef
              type: object
          required:
            - spec
          type: object
      served: true
      storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
