{{- if .Values.worker.enabled }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: batchtransfer-editor
rules:
- apiGroups: ["motion.fybrik.io"]
  resources: ["batchtransfers", "batchtransfers/finalizers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["motion.fybrik.io"]
  resources: ["batchtransfers/status"]
  verbs: ["get", "update", "patch"]
{{- end }}
