{{- if .Values.manager.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: fybrik-config
data:
  PRETTY_LOGGING: {{ .Values.global.prettyLogging | quote }}
  LOGGING_VERBOSITY: {{ .Values.global.loggingVerbosity | quote }}
  RESOURCE_POLLING_INTERVAL: {{ .Values.manager.resourcePollingInterval | quote }}
  DISCOVERY_BURST: {{ .Values.manager.discoveryBurst | quote }}
  DISCOVERY_QPS: {{ .Values.manager.discoveryQPS | quote }}
  MIN_TLS_VERSION:  {{ .Values.manager.tls.minVersion }}
  {{- if .Values.coordinator.enabled }}
  DATAPATH_MAX_SIZE: {{ .Values.manager.dataPathMaxSize | quote }}
  {{- if .Values.manager.solver.image }}
  USE_CSP: {{ .Values.manager.solver.enabled | quote }}
  CSP_ARGS: {{ .Values.manager.solver.args | quote }}
  {{- end }}
  CATALOG_PROVIDER_NAME: {{ .Values.coordinator.catalog | quote }}
  CATALOG_CONNECTOR_URL: {{ .Values.coordinator.catalogConnectorURL | default (printf "http://%s-connector:8080" .Values.coordinator.catalog) | quote }}
  MAIN_POLICY_MANAGER_NAME: {{ .Values.coordinator.policyManager | quote }}
  MAIN_POLICY_MANAGER_CONNECTOR_URL: {{ .Values.coordinator.policyManagerConnectorURL | default (printf "http://%s-connector:8080" .Values.coordinator.policyManager) | quote }}
  STORAGE_MANAGER_URL: {{ printf "http://localhost:%s" .Values.storageManager.serverPort | quote }}
  {{- if .Values.coordinator.vault.enabled }}
  VAULT_ENABLED: "true"
  VAULT_ADDRESS: {{ tpl .Values.coordinator.vault.address . | quote }}
  VAULT_MODULES_ROLE: "module" # temporary
  {{- end }}
  {{- end }}
{{- end }}
