{{- if include "fybrik.isEnabled" (tuple .Values.manager.enabled .Values.worker.enabled) }}
{{- if .Values.modulesNamespace.managedByFybrik }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "fybrik.fullname" . }}-blueprints-rb
  namespace: {{ include "fybrik.getModulesNamespace" . }}
  labels:
    {{- include "fybrik.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "fybrik.fullname" . }}-blueprints-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.manager.serviceAccount.name | default "default" }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
