{{- if .Values.manager.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "fybrik.fullname" . }}-system-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  - secrets
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - leases
  - leases/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.fybrik.io
  resources:
  - plotters
  - blueprints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.fybrik.io
  resources:
  - plotters/status
  - blueprints/status
  - fybrikmodules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - app.fybrik.io
  resources:
  - fybrikstorageaccounts
  - fybrikmodules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
{{- end }}
