{{- if .Values.worker.enabled }}
{{- if .Values.clusterScoped }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: streamtransfer-rb
  namespace: fybrik-blueprints
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: streamtransfer-editor
subjects:
- kind: ServiceAccount
  name: {{ .Values.manager.serviceAccount.name | default "default" }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
