# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

# Default values for m4d-proxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

proxy:
  host: example.com
  egressGateway:
    createPrivate: false
    usePrivate: false
