openapi: 3.0.1
info:
  version: 1.0.0
  title: Data Catalog Service - Asset Details
  license:
    name: Apache 2.0
servers:
  - url: https://localhost:8080
paths:
  /getAssetInfo:
      post:
        summary: getAssetInfo
        parameters:
          - in: header
            name: X-Request-Datacatalog-Cred
            schema:
              type: string
            required: true
        requestBody:
          description: Data Catalog Request Object.
          required: true
          content:
            application/json:
              schema:
                $ref: "../../charts/fybrik/files/taxonomy/data_catalog_request.json"
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: "../../charts/fybrik/files/taxonomy/data_catalog_response.json"
          '400':
            description: Bad request - server cannot process the request due to client error