{{- $autoFlag := and .Values.manager.enabled .Values.coordinator.enabled (eq .Values.coordinator.policyManager "opa") }}
{{- if include "m4d.isEnabled" (tuple .Values.opaConnector.enabled $autoFlag) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa-connector
  labels:
    app.kubernetes.io/component: opa-connector
    {{- include "m4d.labels" . | nindent 4 }}
spec:
  {{- if not .Values.opaConnector.autoscaling.enabled }}
  replicas: {{ .Values.opaConnector.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: opa-connector
      {{- include "m4d.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.opaConnector.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        m4d.ibm.com/componentType: connector
        app.kubernetes.io/component: opa-connector
        {{- include "m4d.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.opaConnector.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.opaConnector.podSecurityContext | nindent 8 }}
      containers:
        - name: opa-connector
          securityContext:
            {{- toYaml .Values.opaConnector.securityContext | nindent 12 }}
          image: {{ include "m4d.image" ( tuple $ .Values.opaConnector ) }}
          imagePullPolicy: {{ .Values.opaConnector.imagePullPolicy | default .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 50082
              protocol: TCP
          envFrom:
            - configMapRef:
                name: opa-connector-config
          resources:
            {{- toYaml .Values.opaConnector.resources | nindent 12 }}
      {{- with .Values.opaConnector.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.opaConnector.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.opaConnector.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
