{{- $autoFlag := and .Values.coordinator.enabled (eq .Values.coordinator.policyManager "opa") }}
{{- if include "fybrik.isEnabled" (tuple .Values.opaConnector.enabled $autoFlag) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa-connector
  labels:
    app.kubernetes.io/component: opa-connector
    {{- include "fybrik.labels" . | nindent 4 }}
spec:
  {{- if not .Values.opaConnector.autoscaling.enabled }}
  replicas: {{ .Values.opaConnector.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: opa-connector
      {{- include "fybrik.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.opaConnector.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        fybrik.io/componentType: connector
        app.kubernetes.io/component: opa-connector
        {{- include "fybrik.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.opaConnector.serviceAccount.name }}
      securityContext:
      {{- include "fybrik.processPodSecurityContext" (dict "context" . "podSecurityContext" .Values.opaConnector.podSecurityContext) | nindent 8 }}
      containers:
        - name: opa-connector
          securityContext:
            {{- mergeOverwrite (deepCopy .Values.global.containerSecurityContext) .Values.opaConnector.containerSecurityContext | toYaml | nindent 12 }}
          image: {{ include "fybrik.image" ( tuple $ .Values.opaConnector ) }}
          imagePullPolicy: {{ .Values.opaConnector.imagePullPolicy | default .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: DATA_DIR
              value: {{ include "fybrik.getDataDir" . }}
            - name: SERVICE_PORT
              value: {{ .Values.opaConnector.service.port | quote }}
            - name: USE_TLS
              value: {{ .Values.opaConnector.tls.use_tls | quote | toString }}
            - name: USE_MTLS
              value: {{ .Values.opaConnector.tls.use_mtls | quote | toString }}
            - name: TLS_MIN_VERSION
              value: {{ .Values.opaConnector.tls.minVersion }}
          envFrom:
            - configMapRef:
                name: opa-connector-config
          volumeMounts:
            - name: data
              mountPath: {{ include "fybrik.getDataDir" . }}
            {{- if .Values.opaConnector.tls.certs.certSecretName }}
            - mountPath: {{ include "fybrik.getDataSubdir" ( tuple "tls-cert" ) }}
              name: tls-cert
              readOnly: true
            {{- end }}
            {{- if .Values.opaConnector.tls.certs.cacertSecretName }}
            - mountPath: {{ include "fybrik.getDataSubdir" ( tuple "tls-cacert" ) }}
              name: tls-cacert
              readOnly: true
            {{- end }}

          resources:
            {{- toYaml .Values.opaConnector.resources | nindent 12 }}
      {{- with .Values.opaConnector.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.opaConnector.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.opaConnector.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: data
          emptyDir:
            sizeLimit: {{ .Values.opaConnector.dataDirSizeLimit }}
        {{- if .Values.opaConnector.tls.certs.certSecretName }}
        - name: tls-cert
          secret:
            defaultMode: 420
            secretName: {{ .Values.opaConnector.tls.certs.certSecretName }}
        {{- end }}
        {{- if .Values.opaConnector.tls.certs.cacertSecretName }}
        - name: tls-cacert
          secret:
            defaultMode: 420
            secretName: {{ .Values.opaConnector.tls.certs.cacertSecretName }}
        {{- end }}
{{- end }}
