{{- $autoFlag := and .Values.coordinator.enabled (eq .Values.coordinator.policyManager "opa") }}
{{- if include "fybrik.isEnabled" (tuple .Values.opaConnector.enabled $autoFlag) }}
apiVersion: v1
kind: Service
metadata:
  name: opa-connector
  labels:
    app.kubernetes.io/component: opa-connector
    {{- include "fybrik.labels" . | nindent 4 }}
spec:
  type: {{ .Values.opaConnector.service.type }}
  ports:
    - port: {{ .Values.opaConnector.service.port }}
      protocol: TCP
      {{- if include "fybrik.isTLSPort" ( tuple .Values.opaConnector.service.port ) }}
      name: https
      {{ else }}
      name: http
      {{ end }}
  selector:
    app.kubernetes.io/component: opa-connector
    {{- include "fybrik.selectorLabels" . | nindent 4 }}
{{- end }}
