{{- $autoFlag := and .Values.coordinator.enabled (eq .Values.coordinator.policyManager "opa") }}
{{- if include "m4d.isEnabled" (tuple .Values.opaConnector.enabled $autoFlag) }}
{{- if .Values.opaConnector.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.opaConnector.serviceAccount.name }}
  labels:
    app.kubernetes.io/component: opa-connector
    {{- include "m4d.labels" . | nindent 4 }}
  {{- with .Values.opaConnector.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
