{{- $autoFlag := and .Values.coordinator.enabled (eq .Values.coordinator.policyManager "opa") }}
{{- if include "fybrik.isEnabled" (tuple .Values.opaConnector.enabled $autoFlag) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa-connector
  labels:
    app.kubernetes.io/component: opa-connector
    {{- include "fybrik.labels" . | nindent 4 }}
spec:
  {{- if not .Values.opaConnector.autoscaling.enabled }}
  replicas: {{ .Values.opaConnector.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: opa-connector
      {{- include "fybrik.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.opaConnector.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        fybrik.io/componentType: connector
        app.kubernetes.io/component: opa-connector
        {{- include "fybrik.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.opaConnector.serviceAccount.name }}
      {{- if not .Values.global.openshift }}
      securityContext:
        {{- mergeOverwrite .Values.global.podSecurityContext .Values.opaConnector.podSecurityContext | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: opa-connector
          {{- if not .Values.global.openshift }}
          securityContext:
            {{- mergeOverwrite .Values.global.containerSecurityContext .Values.opaConnector.containerSecurityContext | toYaml | nindent 12 }}
          {{- end }}
          image: {{ include "fybrik.image" ( tuple $ .Values.opaConnector ) }}
          imagePullPolicy: {{ .Values.opaConnector.imagePullPolicy | default .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: opa-connector-config
          resources:
            {{- toYaml .Values.opaConnector.resources | nindent 12 }}
      {{- with .Values.opaConnector.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.opaConnector.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.opaConnector.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
