{{- $autoFlag := and .Values.coordinator.enabled (eq .Values.coordinator.catalog "egeria") }}
{{- if include "m4d.isEnabled" (tuple .Values.egeriaConnector.enabled $autoFlag) }}
{{- if .Values.egeriaConnector.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.egeriaConnector.serviceAccount.name }}
  labels:
    app.kubernetes.io/component: egeria-connector
    {{- include "m4d.labels" . | nindent 4 }}
  {{- with .Values.egeriaConnector.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
