vault:
  global:
    enabled: true
    tlsDisable: false

  standalone:
      enabled: true

  server:
    extraEnvironmentVars:
      VAULT_CACERT: /vault/userconfig/vault-server-tls/ca.crt

    standalone:
      config: |
        plugin_directory = "/usr/local/libexec/vault"
        ui = true
        listener "tcp" {
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_disable = false
          tls_cert_file = "/vault/userconfig/vault-server-tls/tls.crt"
          tls_key_file  = "/vault/userconfig/vault-server-tls/tls.key"
        }
        # Advertise the non-loopback interface
        api_addr = "[::]:8200" 
        cluster_addr = "[::]:8201"
        storage "file" {
          path = "/vault/data"
        }

    volumes:
      - name: userconfig-vault-server-tls
        secret:
          defaultMode: 420
          secretName: test-tls-vault-certs
      - name: plugins
        emptyDir: {}
      - name: poststartvolume
        emptyDir: {}
      - name: configvolume # this volume is read only
        configMap:
          name: vault-poststart-cm
          defaultMode: 0744
    volumeMounts:
      - mountPath: /vault/userconfig/vault-server-tls
        name: userconfig-vault-server-tls
        readOnly: true
      - mountPath: /usr/local/libexec/vault
        name: plugins
        readOnly: false
      - mountPath: /opt/config
        name: poststartvolume
        readOnly: false
      - mountPath: /etc/config/poststart.sh
        subPath: poststart.sh
        name: configvolume
    extraInitContainers:
      - name: kubesecrets-plugin
        image: ghcr.io/fybrik/vault-plugin-secrets-kubernetes-reader:0.5.0
        command: [/bin/sh, -ec]
        args:
          - |
            cp /vault-plugin-secrets-kubernetes-reader /usr/local/libexec/vault/vault-plugin-secrets-kubernetes-reader
            cp /etc/config/poststart.sh /opt/config/poststart.sh
        volumeMounts:
        - name: plugins
          mountPath: /usr/local/libexec/vault
          readOnly: false
        - name: poststartvolume
          mountPath: /opt/config
          readOnly: false
        - name: configvolume
          mountPath: /etc/config
          readOnly: false
      # Used to define commands to run after the pod is ready.
      # This can be used to automate processes such as initialization
      # or boostrapping auth methods.
    postStart:
      - "sh"
      - "-c"
      - |
        # Sleep command is needed to avoid synchronization issues with the container pod. Please see
        # https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/#discussion
        # FIXME: Use a proper way to configure Vault after Vault start-up
        sleep 5
        # Unseal the server
        # FIXME: A proper way to configure vault is as follows: the root token needs to be used for configuring Vault 
        # roles and policies and then be discarded. (it can be re-created using unseal keys later if needed)
        # ref: https://learn.hashicorp.com/tutorials/vault/production-hardening
        # Set VAULT_SKIP_VERIFY option to avoid CA certificate check in the client. This can be avoided by setting VAULT_CACERT option,
        # given that the ca certificate contains the IP of vault pod.
        export VAULT_SKIP_VERIFY=true
        rm -rf /vault/data/*
        vault operator init | tee /tmp/vault.init > /dev/null
        cat /tmp/vault.init | grep '^Unseal' | awk '{print $4}' | for key in $(cat -); do
          vault operator unseal $key
        done
        token=`cat /tmp/vault.init | grep 'Initial Root Token:' | awk '{print $4}'`; vault login $token
        rm -rf /tmp/vault.init
        /opt/config/poststart.sh

