name: Build

on:
  push:
    branches:
      - github_actions_tests
#  pull_request:
#    branches:
#      - master

env:
  DOCKER_HOSTNAME: ghcr.io
  DOCKER_USERNAME: the-mesh-for-data
  ACTIVE_CI: travisci # This parameter defines which CI should push to the docker repository

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    env:
      DOCKER_HOSTNAME: "localhost:5000"
      DOCKER_NAMESPACE: m4d-system
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
    - uses: actions/checkout@v2
    - run: echo $GOPATH
    - run: echo $GOROOT
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
          ~/go/pkg/mod
          ${{ github.workspace }}/hack/tools/bin
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go
    - run: ls -lah ${{ github.workspace }}/hack/tools/bin || true
    - name: Verify
      run: make verify

  test:
    name: Unit tests
    runs-on: ubuntu-latest
    env:
      DOCKER_HOSTNAME: "localhost:5000"
      DOCKER_NAMESPACE: m4d-system
    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
    - uses: actions/checkout@v2
    - run: echo $GOPATH
    - run: echo $GOROOT
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
          ~/go/pkg/mod
          ${{ github.workspace }}/hack/tools/bin
        key: ${{ runner.os }}-ut-m2-${{ hashFiles('**/pom.xml') }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-ut-m2
    - run: ls -lah ${{ github.workspace }}/hack/tools/bin || true
    - name: Test
      run: make test

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    env:
      DOCKER_HOSTNAME: "localhost:5000"
      DOCKER_NAMESPACE: m4d-system
    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
    - uses: actions/checkout@v2
    - run: echo $GOPATH
    - run: echo $GOROOT
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
          ~/go/pkg/mod
          ${{ github.workspace }}/hack/tools/bin
        key: ${{ runner.os }}-it-m2-${{ hashFiles('**/pom.xml') }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-it-m2
    - run: ls -lah ${{ github.workspace }}/hack/tools/bin || true
    - run: du -sh ~/go/pkg/mod || true
    - run: du -sh ~/.m2/repository || true
    - name: Install tools
      run: make install-tools
    - name: Integration tests
      run: make run-integration-tests
    - run: docker images
    - name: Save images
      if: ${{ github.event_name != 'pull_request' && env.ACTIVE_CI == 'gh_actions' }}
      run: make save-images
    - name: Upload images
      if: ${{ github.event_name != 'pull_request' && env.ACTIVE_CI == 'gh_actions' }}
      uses: actions/upload-artifact@v2
      with:
        name: images
        path: images.tar
        retention-days: 1

  push_images:
    name: Push images
    runs-on: ubuntu-latest
    env:
      DOCKER_HOSTNAME: "localhost:5000"
      DOCKER_NAMESPACE: m4d-system
    needs: [verify, test, integration-tests]
    if: ${{ github.event_name != 'pull_request' }}
    steps:
    - uses: actions/checkout@v2
    - name: Download artifact
      if: ${{ github.event_name != 'pull_request' && env.ACTIVE_CI == 'gh_actions' }}
      uses: actions/download-artifact@v2
      with:
        name: images
    - name: Load images
      if: ${{ github.event_name != 'pull_request' && env.ACTIVE_CI == 'gh_actions' }}
      run: docker load -i images.tar
    - run: docker images
    - name: Publish images
      if: ${{ github.event_name != 'pull_request' && env.ACTIVE_CI == 'gh_actions' }}
      run: sudo chmod o+x /etc/docker && make docker-retag-and-push-public && make helm-push-public

  build_website:
    name: Build website
    runs-on: ubuntu-latest
    env:
      WEBSITE_LOCAL_DIR: public
    steps:
    - name: Install asciidoctor
      run: sudo apt-get -y install asciidoctor
    - uses: actions/checkout@v2
    - name: Cache binaries
      uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ${{ github.workspace }}/hack/tools/bin
        key: ${{ runner.os }}-web-${{ hashFiles('hack/tools/bin/*') }}
        restore-keys: ${{ runner.os }}-it-m2
    - name: Create website
      run: make -C website
    - name: Upload website artifact
      if: ${{ github.event_name != 'pull_request' && env.ACTIVE_CI == 'gh_actions' }}
      uses: actions/upload-artifact@v2
      with:
        name: website
        path: website/${{ env.WEBSITE_LOCAL_DIR }}
        retention-days: 1

  publish_website:
    name: Publish website
    runs-on: ubuntu-latest
    env:
      WEBSITE_LOCAL_DIR: public
    needs: [verify, test, integration-tests, build_website]
    if: ${{ github.event_name != 'pull_request' }}
    steps:
    - uses: actions/checkout@v2
    - name: Download website artifact
      if: ${{ github.event_name != 'pull_request' && env.ACTIVE_CI == 'gh_actions' }}
      uses: actions/download-artifact@v2
      with:
        name: website
    - name: Publish website
      if: ${{ github.event_name != 'pull_request' && env.ACTIVE_CI == 'gh_actions' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: website/${{ env.WEBSITE_LOCAL_DIR }}
        publish_branch: gh-pages