name: Update Charts

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Update Charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3
        with:
          path: main
      - name: Checkout charts repository
        uses: actions/checkout@v3
        with:
          repository: fybrik/charts
          path: charts-repo
      - run: |
          rm -rf charts-repo/charts/fybrik-crd
          rm -rf charts-repo/charts/fybrik
          rm -rf charts-repo/charts/vault
          cp -r main/charts/fybrik-crd charts-repo/charts
          cp -r main/charts/fybrik charts-repo/charts
          cp -r main/charts/vault charts-repo/charts
      - uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.FYBRIK_BOT_APP_ID }}
          private_key: ${{ secrets.FYBRIK_BOT_PRIVATE_KEY }}
          repository: fybrik/charts
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          path: charts-repo
          signoff: true
          token: ${{ steps.generate-token.outputs.token }}
          title: 'Update charts to new release'
          commit-message: Update charts
          committer: GitHub <noreply@github.com>
          delete-branch: true
