name: Update Operate First directory

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Update Operate First directory
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fybrik repository
        uses: actions/checkout@v2
        with:
          repository: fybrik/fybrik
          path: fybrik-repo
      - name: Checkout original Operate First repository
        uses: actions/checkout@v2
        with:
          repository: operate-first/apps
          path: operate-first-repo
      - run: |
          rm -r fybrik-repo/integration/operate-first/*/
          pushd fybrik-repo/hack/tools && ./install_yq.sh && ./install_helm.sh && popd
          pushd fybrik-repo/integration/operate-first
          make helm-template
          pip install pipenv
          pipenv install
          pipenv run python filterClusterScoped.py
          rm ./*.yaml && popd
          rsync -a --include='*/' --include='*.yaml' --exclude='*' fybrik-repo/integration/operate-first/ operate-first-repo/cluster-scope/base
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          path: operate-first-repo
          signoff: true
          token: ${{ secrets.PERSONAL_TOKEN }}
          push-to-fork: eletonia/apps
          title: 'Update Operate First files to new release'
          commit-message: Update Fybrik cluster-scoped resources for Operate First
          committer: GitHub <noreply@github.com>
          delete-branch: true