name: Update Operate First directory

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Update Operate First directory
    runs-on: ubuntu-latest
    steps:
      - name: Checkout forked Operate First repository
        uses: actions/checkout@v2
        with:
          repository: fybrik/operate-first-apps
          path: operate-first-fork
      - name: Checkout Fybrik repository
        uses: actions/checkout@v2
        with:
          repository: fybrik/fybrik
          path: fybrik-repo
      - run: |
          rm -r fybrik-repo/samples/operate-first/*/
          rm fybrik-repo/samples/operate-first/*.yaml
          pushd fybrik-repo/hack/tools && ./install_yq.sh && ./install_helm.sh && popd
          pushd fybrik-repo/samples/operate-first
          make helm-template
          pip install pipenv
          pipenv install
          pipenv run python filterClusterScoped.py
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.CHARTS_APP_ID }}
          private_key: ${{ secrets.CHARTS_APP_PRIVATE_KEY  }}
          repository: fybrik/fybrik
      - name: Push Pull Request Branch to Fork
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          push-to-fork: fybrik/operate-first-apps
      - name: Checkout original Operate First repository
        uses: actions/checkout@v2
        with:
          repository: operate-first/apps
          path: operate-first-repo
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          path: operate-first-repo
          signoff: true
          token: ${{ steps.generate-token.outputs.token }}
          title: 'Update Operate First files to new release'
          commit-message: Update Fybrik cluster-scoped resources for Operate First
          committer: GitHub <noreply@github.com>
          delete-branch: true