name: Website Deploy
on:
  push:
    tags:
      - 'v*'
    branches:
      - master
    paths:
      - site/**
      - .github/workflows/website-*
      - pkg/connectors/protos/**
      - charts/fybrik-crd/templates/**
  workflow_dispatch:
jobs:
  website-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Material for MkDocs
        run: |
          pip install mkdocs-material
          pip install mike
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "noreply@github.com"
      - id: version
        name: Infer version
        run: echo ::set-output name=version::$(cut -d '.' -f 1,2 <<< "${GITHUB_REF#refs/*/}")
      - name: Build and Deploy (dev)
        if: steps.version.outputs.version == 'master'
        working-directory: ./site
        run: mike deploy --push --remote origin --branch site dev
      - name: Build and Deploy (tag)
        if: steps.version.outputs.version != 'master'
        working-directory: ./site
        run: mike deploy --push --update-aliases --remote origin --branch site ${{ steps.version.outputs.version }} latest
